#!/usr/bin/env bash
set -e
#!/usr/bin/env bash
set -e

function usage() {
    echo "Usage: gh assignments [classroom name]"
    echo "Description: List of assignments"
}
# if option is -h or --help, then show help
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit 0
fi
ORGANIZATION=$(gh pwd)
if [ -n "$1" ]; then
  ORGANIZATION=$1
fi
CLASSROOM=$(gh classroom list --per-page 200 | grep $ORGANIZATION | awk '{print $1}')
if [ -z "$CLASSROOM" ]; then
    echo "No classroom \"$ORGANIZATION\" found"
    exit 1
else
  gh classroom assignments list -c $CLASSROOM --per-page 300 
fi
